version: 0.4.0-beta_build_{build}
configuration: Release

before_build:
- cmd: nuget restore 

assembly_info: 
  patch: true 
  file: AssemblyInfo.* 
  assembly_version: "{version}" 
  assembly_file_version: "{version}" 
  assembly_informational_version: "{version}"

build:
  project: Pk.Signals.sln
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true

environment:
  COVERALLS_REPO_TOKEN:
    secure: crJHxRdsmThmLkiRxWKYiaO5BUz6YitMCH5aspHEqpkfiQAKfxjKDmCS1bE6aX1H

test_script:
  - ps: .\tests\run_tests.bat

after_test:
  - cmd: .\libraries\Nuget\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[Pk.*]* -[Pk.*.Tests.*]*" -target:".\libraries\Nuget\xunit.runner.console.2.1.0\tools\xunit.console.exe" -targetargs:".\tests\Pk.Signals.Tests\bin\Release\Pk.Signals.Tests.dll -noshadow -nologo" -output:coverage.xml
  - cmd: .\libraries\Nuget\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml


artifacts:
  - path: .\coverage.xml
  - path: .\xunit-results.xml

  
deploy:
  provider: NuGet
  api_key:
    secure: BUCXu9ZvnXlGLJHtJTxMDa8nT3UavyVq8azak1NAfiYBLkd/x1n37p+WPB8wSP8i
  artifact: /.*\.nupkg/
  on:
    branch: develop
